import { describe, it, expect } from 'vitest'
import {
  encodeWavMonoPcm16,
  assembleChapterAudio,
  formatMp3Name,
  buildId3v2Tags,
} from '../audio'
import type { Character } from '../characters'
import type { AudioSegment } from '../tts'

const narrator: Character = {
  id: 'narrator',
  displayName: 'Narrator',
  isNarrator: true,
  voiceId: 'neutral',
  confidence: 1,
}
const xiaoyu: Character = {
  id: 'char-xiaoyu',
  displayName: '小瑜',
  isNarrator: false,
  voiceId: 'female-1',
  confidence: 0.9,
}

function fakeSegment(voiceId: string, durationMs: number, sampleRateHz = 16000): AudioSegment {
  const numSamples = Math.round((durationMs / 1000) * sampleRateHz)
  const bytes = new Uint8Array(numSamples * 2).fill(0x42)
  return { voiceId, bytes, durationMs, sampleRateHz, provider: 'mock' }
}

describe('audio module — SPEC §3 FR-003 chapter MP3 + ID3 tags', () => {
  describe('formatMp3Name', () => {
    it('produces "book-slug-chapter-XX.mp3" with 2-digit padding', () => {
      expect(formatMp3Name('my-book', 1)).toBe('my-book-chapter-01.mp3')
      expect(formatMp3Name('my-book', 9)).toBe('my-book-chapter-09.mp3')
      expect(formatMp3Name('my-book', 10)).toBe('my-book-chapter-10.mp3')
    })

    it('handles Traditional Chinese in slug', () => {
      expect(formatMp3Name('小說-冒險', 1)).toBe('小說-冒險-chapter-01.mp3')
    })
  })

  describe('encodeWavMonoPcm16', () => {
    it('writes a 44-byte WAV header followed by raw PCM', () => {
      const pcm = new Uint8Array(20) // 10 samples
      const wav = encodeWavMonoPcm16(pcm, 16000)
      expect(wav.length).toBe(64)
      // RIFF
      expect(String.fromCharCode(wav[0], wav[1], wav[2], wav[3])).toBe('RIFF')
      expect(String.fromCharCode(wav[8], wav[9], wav[10], wav[11])).toBe('WAVE')
      expect(String.fromCharCode(wav[12], wav[13], wav[14], wav[15])).toBe('fmt ')
      expect(String.fromCharCode(wav[36], wav[37], wav[38], wav[39])).toBe('data')
    })

    it('uses the requested sample rate in the fmt chunk', () => {
      const wav = encodeWavMonoPcm16(new Uint8Array(4), 22050)
      const view = new DataView(wav.buffer)
      expect(view.getUint32(24, true)).toBe(22050)
    })

    it('handles an empty PCM payload (header only, 44 bytes)', () => {
      const wav = encodeWavMonoPcm16(new Uint8Array(0), 16000)
      expect(wav.length).toBe(44)
    })
  })

  describe('assembleChapterAudio', () => {
    it('returns empty markers and 0 duration when segments are empty', () => {
      const audio = assembleChapterAudio({
        bookTitle: 'Test',
        bookSlug: 'test',
        chapterNumber: 1,
        chapterTitle: '第一章',
        segments: [],
      })
      expect(audio.durationMs).toBe(0)
      expect(audio.markers).toEqual([])
      expect(audio.wavBytes.length).toBe(0)
    })

    it('concatenates PCM from multiple segments in order', () => {
      const audio = assembleChapterAudio({
        bookTitle: 'Test',
        bookSlug: 'test',
        chapterNumber: 1,
        chapterTitle: '第一章',
        segments: [
          { character: narrator, segment: fakeSegment('neutral', 1000) },
          { character: xiaoyu, segment: fakeSegment('female-1', 2000) },
        ],
      })
      expect(audio.durationMs).toBe(3000)
      // Header (44) + PCM (1s + 2s of 16kHz 16-bit mono)
      const expectedPcmSamples = (1000 + 2000) / 1000 * 16000 * 2
      expect(audio.wavBytes.length).toBe(44 + expectedPcmSamples)
    })

    it('builds chapter markers with start/end offsets in ms', () => {
      const audio = assembleChapterAudio({
        bookTitle: 'Test',
        bookSlug: 'test',
        chapterNumber: 1,
        chapterTitle: '第一章',
        segments: [
          { character: narrator, segment: fakeSegment('neutral', 500) },
          { character: xiaoyu, segment: fakeSegment('female-1', 1500) },
          { character: narrator, segment: fakeSegment('neutral', 300) },
        ],
      })
      expect(audio.markers).toHaveLength(3)
      expect(audio.markers[0]).toMatchObject({ startMs: 0, endMs: 500, label: 'Narrator' })
      expect(audio.markers[1]).toMatchObject({ startMs: 500, endMs: 2000, label: '小瑜' })
      expect(audio.markers[2]).toMatchObject({ startMs: 2000, endMs: 2300, label: 'Narrator' })
    })

    it('writes ID3 tags with title/artist/album/track (FR-003)', () => {
      const audio = assembleChapterAudio({
        bookTitle: '冒險之旅',
        bookSlug: 'adventure',
        chapterNumber: 3,
        chapterTitle: '第三章 出發',
        author: '小說家 Sean',
        segments: [{ character: narrator, segment: fakeSegment('neutral', 1000) }],
      })
      expect(audio.id3).toEqual({
        title: '第三章 出發',
        artist: '小說家 Sean',
        album: '冒險之旅',
        trackNumber: 3,
        comment: 'Generated by ebook-to-audiobook',
      })
    })

    it('uses "Unknown" as artist when none provided', () => {
      const audio = assembleChapterAudio({
        bookTitle: 'Book',
        bookSlug: 'book',
        chapterNumber: 1,
        chapterTitle: 'Chapter 1',
        segments: [{ character: narrator, segment: fakeSegment('v', 500) }],
      })
      expect(audio.id3.artist).toBe('Unknown')
    })

    it('produces a valid WAV file with "RIFF"/"WAVE"/"data" markers', () => {
      const audio = assembleChapterAudio({
        bookTitle: 'Test',
        bookSlug: 'test',
        chapterNumber: 1,
        chapterTitle: 'Chapter 1',
        segments: [{ character: narrator, segment: fakeSegment('v', 500) }],
      })
      const s = String.fromCharCode(...audio.wavBytes.slice(0, 12).values ? audio.wavBytes.slice(0, 12) : [])
      // Simpler: just check magic bytes individually
      expect(audio.wavBytes[0]).toBe(0x52) // 'R'
      expect(audio.wavBytes[1]).toBe(0x49) // 'I'
      expect(audio.wavBytes[2]).toBe(0x46) // 'F'
      expect(audio.wavBytes[3]).toBe(0x46) // 'F'
      expect(audio.wavBytes[8]).toBe(0x57) // 'W'
      expect(audio.wavBytes[9]).toBe(0x41) // 'A'
      expect(audio.wavBytes[10]).toBe(0x56) // 'V'
      expect(audio.wavBytes[11]).toBe(0x45) // 'E'
      // silence the unused-variable warning
      void s
    })
  })

  describe('buildId3v2Tags', () => {
    it('starts with the ID3v2.3 magic "ID3"', () => {
      const audio = assembleChapterAudio({
        bookTitle: 'Test',
        bookSlug: 'test',
        chapterNumber: 1,
        chapterTitle: 'Chapter 1',
        segments: [{ character: narrator, segment: fakeSegment('v', 500) }],
      })
      const tags = buildId3v2Tags(audio)
      expect(tags.startsWith('ID3')).toBe(true)
    })

    it('includes the chapter count in the JSON summary', () => {
      const audio = assembleChapterAudio({
        bookTitle: 'Test',
        bookSlug: 'test',
        chapterNumber: 1,
        chapterTitle: 'Chapter 1',
        segments: [
          { character: narrator, segment: fakeSegment('v', 500) },
          { character: xiaoyu, segment: fakeSegment('v', 800) },
        ],
      })
      const tags = buildId3v2Tags(audio)
      expect(tags).toContain('"chapterCount":2')
      expect(tags).toContain('"track":1')
    })
  })
})
