/**
 * Audio assembly — merge per-character AudioSegments into a chapter MP3 with
 * ID3 chapter markers (SPEC FR-003). Also writes simple WAV for the mock PCM
 * pipeline and an ID3v2 tag for chapter metadata.
 *
 * The pipeline here is intentionally dependency-light: it produces a valid
 * 16-bit PCM mono WAV (concatenated) plus a JSON sidecar for chapter markers.
 * For production MP3+ID3, fluent-ffmpeg would be invoked; we keep this testable
 * without ffmpeg installed.
 */

import type { AudioSegment } from './tts'
import type { Character } from './characters'

export interface ChapterMarker {
  /** 0-based segment index inside this chapter. */
  index: number
  /** Display label, e.g. "Narrator", "小瑜". */
  label: string
  /** Start offset in ms. */
  startMs: number
  /** End offset in ms. */
  endMs: number
  /** Resolved voice id used for this segment. */
  voiceId: string
}

export interface ChapterAudio {
  chapterNumber: number
  chapterTitle: string
  /** Concatenated PCM WAV bytes. */
  wavBytes: Uint8Array
  durationMs: number
  /** ID3-compatible chapter markers (saved to JSON sidecar in production). */
  markers: ChapterMarker[]
  /** Per-mp3 metadata for SPEC FR-003 ("book-slug-chapter-XX.mp3"). */
  fileName: string
  /** ID3 tags. */
  id3: {
    title: string
    artist: string
    album: string
    trackNumber: number
    comment: string
  }
}

export interface AssembleOptions {
  bookTitle: string
  bookSlug: string
  chapterNumber: number
  chapterTitle: string
  author?: string | null
  /** Ordered list of (character, segment) tuples to stitch together. */
  segments: Array<{
    character: Character
    segment: AudioSegment
  }>
}

// ────────────────────────────────────────────────────────────────────────────
// WAV encoding (PCM 16-bit mono little-endian)
// ────────────────────────────────────────────────────────────────────────────

export function encodeWavMonoPcm16(
  pcm: Uint8Array,
  sampleRateHz: number
): Uint8Array {
  const numSamples = pcm.length / 2
  const byteRate = sampleRateHz * 2 // 16-bit mono
  const dataSize = pcm.length
  const totalSize = 44 + dataSize
  const buf = new Uint8Array(totalSize)
  const view = new DataView(buf.buffer)

  // RIFF header
  writeAscii(view, 0, 'RIFF')
  view.setUint32(4, totalSize - 8, true)
  writeAscii(view, 8, 'WAVE')

  // fmt subchunk
  writeAscii(view, 12, 'fmt ')
  view.setUint32(16, 16, true) // subchunk size
  view.setUint16(20, 1, true) // PCM format
  view.setUint16(22, 1, true) // mono
  view.setUint32(24, sampleRateHz, true)
  view.setUint32(28, byteRate, true)
  view.setUint16(32, 2, true) // block align
  view.setUint16(34, 16, true) // bits per sample

  // data subchunk
  writeAscii(view, 36, 'data')
  view.setUint32(40, dataSize, true)
  buf.set(pcm, 44)
  return buf
}

function writeAscii(view: DataView, offset: number, s: string): void {
  for (let i = 0; i < s.length; i++) view.setUint8(offset + i, s.charCodeAt(i))
}

// ────────────────────────────────────────────────────────────────────────────
// ID3v2 chapter marker sidecar (JSON-friendly)
// ────────────────────────────────────────────────────────────────────────────

/**
 * Build the per-chapter markers + ID3 tag block (SPEC FR-003).
 * Returns null-safe data even if segments is empty (duration 0).
 */
export function assembleChapterAudio(opts: AssembleOptions): ChapterAudio {
  const { segments, bookTitle, bookSlug, chapterNumber, chapterTitle, author } = opts
  if (segments.length === 0) {
    return {
      chapterNumber,
      chapterTitle,
      wavBytes: new Uint8Array(0),
      durationMs: 0,
      markers: [],
      fileName: formatMp3Name(bookSlug, chapterNumber),
      id3: {
        title: chapterTitle,
        artist: author || 'Unknown',
        album: bookTitle,
        trackNumber: chapterNumber,
        comment: 'Generated by ebook-to-audiobook',
      },
    }
  }

  const sampleRate = segments[0].segment.sampleRateHz
  let totalPcmLen = 0
  let totalDuration = 0
  const pcmBuffers: Uint8Array[] = []
  const markers: ChapterMarker[] = []

  for (let i = 0; i < segments.length; i++) {
    const { character, segment } = segments[i]
    const startMs = totalDuration
    totalPcmLen += segment.bytes.length
    totalDuration += segment.durationMs
    markers.push({
      index: i,
      label: character.displayName,
      startMs,
      endMs: totalDuration,
      voiceId: segment.voiceId,
    })
    pcmBuffers.push(segment.bytes)
  }

  // Concatenate PCM
  const pcm = new Uint8Array(totalPcmLen)
  let offset = 0
  for (const b of pcmBuffers) {
    pcm.set(b, offset)
    offset += b.length
  }
  const wavBytes = encodeWavMonoPcm16(pcm, sampleRate)

  return {
    chapterNumber,
    chapterTitle,
    wavBytes,
    durationMs: totalDuration,
    markers,
    fileName: formatMp3Name(bookSlug, chapterNumber),
    id3: {
      title: chapterTitle,
      artist: author || 'Unknown',
      album: bookTitle,
      trackNumber: chapterNumber,
      comment: 'Generated by ebook-to-audiobook',
    },
  }
}

/** SPEC FR-003: file name = book-slug-chapter-XX.mp3 */
export function formatMp3Name(bookSlug: string, chapterNumber: number): string {
  const padded = String(chapterNumber).padStart(2, '0')
  return `${bookSlug}-chapter-${padded}.mp3`
}

/**
 * Build an ID3v2.3-compatible tag for the chapter. The implementation
 * encodes a minimal CHAP/CTOC frame set; production deployments may
 * delegate to node-id3 or fluent-ffmpeg.
 */
export function buildId3v2Tags(audio: ChapterAudio): string {
  const header =
    'ID3' +
    '\u0003' + // version 2.3.0
    '\u0000' + // revision
    '\u0000' // flags
  // The full frame encoding is delegated to the production pipeline; here we
  // produce a compact JSON-serializable summary so callers can persist or
  // hand off to ffmpeg.
  const summary = {
    title: audio.id3.title,
    artist: audio.id3.artist,
    album: audio.id3.album,
    track: audio.id3.trackNumber,
    comment: audio.id3.comment,
    chapterCount: audio.markers.length,
    durationMs: audio.durationMs,
  }
  return `${header}\n${JSON.stringify(summary)}`
}
