import { NextResponse } from 'next/server'
import { buildRssXml } from '@/lib/engine/rss'
import { regenerateRssToken } from '@/lib/engine/rss'

/**
 * GET /api/rss/demo
 *
 * Demo podcast RSS feed powered by the new engine module.
 * No auth required — useful for showcasing the SPEC §3 FR-004 pipeline
 * without configuring Supabase/Stripe/ElevenLabs.
 */
export const runtime = 'nodejs'

export async function GET(request: Request) {
  const url = new URL(request.url)
  const token = url.searchParams.get('token') || regenerateRssToken()

  const channel = {
    title: 'Ebook-to-Audiobook Demo Podcast',
    author: 'OpenClaw Sophia',
    description:
      'Demo podcast feed generated by the ebook-to-audiobook v3.0 engine. ' +
      'Real feeds are generated per-book after EPUB/PDF upload and TTS synthesis.',
    language: 'zh-TW',
    imageUrl: null,
    link: 'https://ebook-to-audiobook.vercel.app',
    audioBaseUrl: 'https://ebook-to-audiobook.vercel.app/api/audio',
    token,
    episodes: [
      {
        chapterNumber: 1,
        title: '第一章 開始 (Demo)',
        description: '示範章節：故事從這裡開始',
        audioUrl: 'https://ebook-to-audiobook.vercel.app/api/audio/demo-1.mp3',
        durationSeconds: 600,
        pubDate: new Date(),
        fileSizeBytes: 1234567,
      },
      {
        chapterNumber: 2,
        title: '第二章 旅途 (Demo)',
        description: '示範章節：踏上旅途',
        audioUrl: 'https://ebook-to-audiobook.vercel.app/api/audio/demo-2.mp3',
        durationSeconds: 720,
        pubDate: new Date(),
        fileSizeBytes: 1500000,
      },
      {
        chapterNumber: 3,
        title: '第三章 結局 (Demo)',
        description: '示範章節：冒險結束',
        audioUrl: 'https://ebook-to-audiobook.vercel.app/api/audio/demo-3.mp3',
        durationSeconds: 540,
        pubDate: new Date(),
        fileSizeBytes: 1100000,
      },
    ],
  }

  const xml = buildRssXml(channel)
  return new NextResponse(xml, {
    status: 200,
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'public, max-age=60',
    },
  })
}
